spring:
  security:
    user:
      name: ${SECURITY_NAME}
      password: ${SECURITY_PASSWORD}
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test
  app:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: 3600000
    jwtCookieName: ${JWT_COOKIE}
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_MAIL}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
#logging:
#  level:
#    org:
#      springframework: DEBUG
#      security: DEBUG
#      hibernate:
#        SQL: DEBUG
#    pl:
#      ecommerce:
#        project: DEBUG

frontend:
  url: ${FRONT_URL}

cloudinary:
  cloud-name: ${CLOUD_NAME_CLOUDINARY}
  api-key: ${API_KEY_CLOUDINARY}
  api-secret: ${API_SECRET_CLOUDINARY}
  url: cloudinary://${API_KEY_CLOUDINARY}:${API_SECRET_CLOUDINARY}@${CLOUD_NAME_CLOUDINARY}
  default_image: ${DEFAULT_IMAGE_URL}
  path: products

#Stripe key
stripe:
  secret:
    key: ${STRIPE_API_KEY}
